site_name: CARTIFactory
theme:
  name: readthedocs
  logo: images/CARTIF_transparente.png
  palette:
    primary: teal
    accent: light-green
extra_css:
  - stylesheets/custom.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption