# Goal Definition
string kw                           # Keyword, what are we looking for
---
# Result
bool action_success                 # Boolean indicating if the action was completed succesfully
bool match_success                  # Boolean indicating if a match was found or not
# string result_message             # String message, for comunication purposes
vision_msgs/Detection2DArray det    # Detection 
sensor_msgs/Image img               # Image with the detections printed on it
---
# Feedback
string feedback                     # String message, for comunication purposes

